# Generated by Django 3.2.8 on 2022-07-23 18:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user11', models.CharField(max_length=200)),
                ('user22', models.CharField(max_length=200)),
                ('colvo1', models.IntegerField(blank=True, default=None, null=True)),
                ('time1', models.DateTimeField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usvers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('NKO_name', models.CharField(max_length=100)),
                ('phone', models.CharField(default='00000000000', max_length=11)),
                ('is_superuser', models.BooleanField(default=0)),
                ('is_NKO', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(100)])),
                ('price', models.IntegerField()),
                ('category', models.CharField(default='Товар', max_length=200)),
                ('is_saled', models.BooleanField(default=False)),
                ('to_who', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('phot', models.ImageField(default=None, null=True, upload_to='images/')),
                ('wanttobuy', models.CharField(default='Продать', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Complaints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500, validators=[django.core.validators.MinLengthValidator(10)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
