# Generated by Django 4.0.5 on 2023-03-27 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_products_vector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='vector',
        ),
    ]
