# Generated by Django 3.2.8 on 2022-02-17 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_products_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usvers',
            name='usver',
        ),
        migrations.AddField(
            model_name='usvers',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
