# Generated by Django 3.2.8 on 2022-03-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220217_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='Товар', max_length=200),
        ),
    ]
