# Generated by Django 4.0.5 on 2023-03-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_products_v1_products_v10_products_v100_products_v101_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='v0',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
