# Generated by Django 3.2.8 on 2022-03-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='usvers',
            name='phone',
            field=models.CharField(default='00000000000', max_length=11),
        ),
    ]
