# Generated by Django 3.2.8 on 2022-03-24 19:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_usvers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='usver',
            field=models.ForeignKey(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), on_delete=django.db.models.deletion.CASCADE, to='accounts.usvers'),
        ),
    ]
