# Generated by Django 3.2.8 on 2022-03-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_products_usver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='usver',
        ),
    ]
