# Generated by Django 3.2.8 on 2022-03-25 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_products_usver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usvers',
            name='balance',
            field=models.IntegerField(default=0),
        ),
    ]
