# Generated by Django 3.2.8 on 2022-04-12 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_usvers_is_superuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_saled',
            field=models.BooleanField(default=False),
        ),
    ]
