# Generated by Django 3.2.8 on 2022-04-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_products_is_saled'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='to_who',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
