# Generated by Django 3.2.8 on 2022-04-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_products_to_who'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='to_who',
            field=models.CharField(default='', max_length=200),
        ),
    ]
