# Generated by Django 3.2.8 on 2022-04-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_products_to_who'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='to_who',
        ),
    ]
