# Generated by Django 3.2.8 on 2022-05-15 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0017_remove_products_to_who'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='to_who',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.CreateModel(
            name='Transact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colvo', models.IntegerField()),
                ('time', models.TimeField()),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='give_user', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
