# Generated by Django 3.2.8 on 2022-05-15 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20220516_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='to_who',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transact',
            name='colvo',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transact',
            name='time',
            field=models.TimeField(default=None, null=True),
        ),
    ]
