# Generated by Django 3.2.8 on 2022-05-15 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20220516_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='to_who',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='transact',
            name='colvo',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='transact',
            name='time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
