# Generated by Django 3.2.8 on 2022-05-15 23:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0020_auto_20220516_0405'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transact',
            new_name='Transacts',
        ),
        migrations.RenameField(
            model_name='transacts',
            old_name='colvo',
            new_name='colvo1',
        ),
        migrations.RenameField(
            model_name='transacts',
            old_name='time',
            new_name='time1',
        ),
        migrations.RenameField(
            model_name='transacts',
            old_name='user1',
            new_name='user11',
        ),
        migrations.RenameField(
            model_name='transacts',
            old_name='user2',
            new_name='user22',
        ),
    ]
