# Generated by Django 3.2.8 on 2022-05-16 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_auto_20220516_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacts',
            name='user11',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transacts',
            name='user22',
            field=models.CharField(max_length=200),
        ),
    ]
