# Generated by Django 4.0.5 on 2022-06-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20220516_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacts',
            name='time1',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
